# FAIR Metadata System Configuration Template
# This file serves as the template for all configuration files.
# When setup_tool.py runs, it copies this template and customizes it.

# =============================================================================
# REQUIRED SETTINGS
# =============================================================================

# Directory to monitor for file system events
# This is the main directory where the system will watch for new projects and datasets
monitor_path: /app/monitor

# =============================================================================
# OPTIONAL SETTINGS
# =============================================================================

# Custom schema directory path (optional)
# If specified, the system will use custom schemas from this directory
# in addition to the default schemas in ./schemas/
# custom_schema_path: "./custom_schemas"

# =============================================================================
# REMINDER SERVICE CONFIGURATION (for future use)
# =============================================================================

# Enable/disable the proactive metadata reminder service
# reminders:
#   enabled: false
#
#   # How often to check for incomplete datasets (in hours)
#   schedule_interval_hours: 24
#
#   # Notification settings
#     # Channel: console, slack, email
#     channel: "console"
#
#     # Slack webhook URL (required if channel is "slack")
#     # slack_webhook_url: "https://hooks.slack.com/services/..."
#
#     # Email settings (required if channel is "email")
#     # email:
#     #   smtp_server: "smtp.gmail.com"
#     #   smtp_port: 587
#     #   username: "your-email@gmail.com"
#     #   password: "your-app-password"

# =============================================================================
# ADVANCED SETTINGS (optional overrides)
# =============================================================================

# Override default schema paths (usually not needed)
# schema_paths:
#   project_descriptive: "./schemas/project_descriptive.json"
#   dataset_administrative: "./schemas/dataset_administrative_schema.json"
#   dataset_structural: "./schemas/dataset_structural_schema.json"
#   experiment_contextual: "./schemas/experiment_contextual_schema.json"
#   instrument_technical: "./schemas/instrument_technical_schema.json"
#   complete_metadata: "./schemas/complete_metadata_schema.json"

# Logging configuration (optional)
# logging:
#   level: "INFO"  # DEBUG, INFO, WARNING, ERROR
#   format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
#   file: "./logs/fair_metadata.log"  # Optional log file

# API server settings (optional)
# api:
#   host: "0.0.0.0"
#   port: 8000
#   reload: true  # Enable auto-reload for development

# Monitor settings (optional)
# monitor:
#   recursive: true  # Monitor subdirectories recursively
#   ignore_patterns: [".git", ".dvc", "__pycache__", ".DS_Store"]